apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-service
  labels:
    app: stable-diffusion
spec:
  ports:
  - protocol: TCP
    port: 7860
    targetPort: 7860
  selector:
    app: stable-diffusion
  type: LoadBalancer